openapi: 3.0.3
info:
  title: Soyokaze API
  description: API for Soyokaze mobile application
  version: 1.0.0
  contact:
    name: Soyokaze Team
    email: contact@soyokaze.app
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Development serve

paths:
  /users:
    $ref: "./paths/users/users.yaml"
  /users/{id}:
    $ref: "./paths/users/user-id.yaml"

components:
  schemas:
    User:
      $ref: "./components/schemas/user.yaml"
    CreateUserRequest:
      $ref: "./components/schemas/create-user-request.yaml"
    UpdateUserRequest:
      $ref: "./components/schemas/update-user-request.yaml"
    Error:
      $ref: "./components/schemas/common.yaml#/Error"
    PaginationResponse:
      $ref: "./components/schemas/common.yaml#/PaginationResponse"
    UsersListResponse:
      $ref: "./components/schemas/common.yaml#/UsersListResponse"

  parameters:
    UserId:
      $ref: "./components/parameters/user.yaml#/UserId"
    Limit:
      $ref: "./components/parameters/pagination.yaml#/limit"
    Offset:
      $ref: "./components/parameters/pagination.yaml#/offset"

  responses:
    NotFound:
      $ref: "./components/responses/errors.yaml#/NotFound"
    BadRequest:
      $ref: "./components/responses/errors.yaml#/BadRequest"
    Conflict:
      $ref: "./components/responses/errors.yaml#/Conflict"
    InternalError:
      $ref: "./components/responses/errors.yaml#/InternalError"
    UserResponse:
      $ref: "./components/responses/success.yaml#/UserResponse"
    UserCreated:
      $ref: "./components/responses/success.yaml#/UserCreated"
    UserUpdated:
      $ref: "./components/responses/success.yaml#/UserUpdated"
    UserDeleted:
      $ref: "./components/responses/success.yaml#/UserDeleted"
    UsersListResponse:
      $ref: "./components/responses/success.yaml#/UsersListResponse"

tags:
  - name: users
    description: User management operations
