emit:
  - "@typespec/openapi3"
  - "@typespec/json-schema"

options:
  "@typespec/openapi3":
    "output-file": "openapi.yaml"
    "new-line": "lf"
  
  "@typespec/json-schema":
    "int64-strategy": "string"

trace: []
warn-as-error: false
output-dir: "{project-root}/generated"